apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
  - name: postgres
    image: postgres:14.5
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: postgresdb
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: passoword